splitlines instead of split('\n')
Most text editors insert an eol character at the end of a file.  Using a words.txt with an eol at the end produces this error:
Traceback (most recent call last):
  File "genxword.py", line 180, in <module>
    wordlist = [[line.split(':')[0].upper(), line.split(':')[1]] for line in open('words.txt').read().split('\n')]
IndexError: list index out of range

This little change fixes it.